"""Remove picture field from WishlistItem

Revision ID: 67a5c1aa05f4
Revises: 72f978b083c8
Create Date: 2025-09-02 16:01:27.567090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a5c1aa05f4'
down_revision = '72f978b083c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
